{% set name = "femto" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Psivant/femto/archive/{{ version }}.tar.gz
  sha256: 3fb2255c61e83a1bb01ddbfa566b43cbcf86fd5fc8c00a1b7f0430a9c6649cf3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - versioneer
  run:
    - python >=3.10
    - numpy
    - scipy
    - pydantic >=2
    - click
    - cloup
    - pyarrow
    - tqdm
    - pyyaml
    - pandas
    - omegaconf
    - gputil
    - sympy  # evaluating ctx param expressions
    - pymbar >=4
    - mpi4py
    - networkx
    - mdtraj
    - ambertools
    - openmm >=8.1.0
    - seaborn-base
    - tensorboardx
test:
  imports:
    - femto
    - femto.md
    - femto.fe

about:
  home: https://github.com/Psivant/femto
  summary: 'A comprehensive toolkit for predicting free energies'
  description: |
    A framework that aims to offer not only a compact and comprehensive toolkit for predicting binding free 
    energies using methods including ATM and SepTop, but also a full suite of utilities for running advanced 
    simulations using OpenMM, including support for HREMD and REST2.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
  doc_url: https://psivant.github.io/femto/latest/
  dev_url: https://github.com/psivant/femto

extra:
  recipe-maintainers:
    - SimonBoothroyd
