{% set python_min = "3.10" %}
{% set name = "femto" %}
{% set version = "0.3.0rc3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Psivant/femto/archive/0.3.0-rc.3.tar.gz
  sha256: 1e398d10971a2b14800cbcc71d55b57ad3ea04121c2303df2653fb35a350fef6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm >=8
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - pydantic >=2
    - pydantic-units
    - click
    - cloup
    - pyarrow
    - tqdm
    - pyyaml
    - pandas
    - omegaconf
    - gputil
    - sympy
    - pymbar >=4
    - mpi4py
    - networkx
    - mdtraj
    - openmm >=8.1.0
    - openmmforcefields
    - mdtop
    - rdkit
    - seaborn-base
    - tensorboardx
test:
  imports:
    - femto
    - femto.md
    - femto.fe
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/Psivant/femto
  summary: 'A comprehensive toolkit for predicting free energies'
  description: |
    A framework that aims to offer not only a compact and comprehensive toolkit for predicting binding free 
    energies using methods including ATM and SepTop, but also a full suite of utilities for running advanced 
    simulations using OpenMM, including support for HREMD and REST2.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
  doc_url: https://psivant.github.io/femto/latest/
  dev_url: https://github.com/psivant/femto

extra:
  recipe-maintainers:
    - SimonBoothroyd
